---
Name: shoppingcartconfig
---
## Extra DB fields
SilverStripe\Security\Member:
  has_one:
    Cart: SilverCommerce\ShoppingCart\Model\ShoppingCart

## Manage shopping carts from orders admin
SilverCommerce\OrdersAdmin\Admin\OrderAdmin:
  managed_models:
    - SilverCommerce\OrdersAdmin\Model\Invoice
    - SilverCommerce\OrdersAdmin\Model\Estimate
    - SilverCommerce\ShoppingCart\Model\ShoppingCart

## Extensions
SilverStripe\Control\Controller:
  extensions:
    - SilverCommerce\ShoppingCart\Extensions\ControllerExtension
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - SilverCommerce\ShoppingCart\Extensions\SiteConfigExtension