---
Name: shoppingcartconfig
---
## Extensions
SilverStripe\Control\Controller:
  extensions:
    - SilverCommerce\ShoppingCart\Extensions\ControllerExtension
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - SilverCommerce\ShoppingCart\Extensions\SiteConfigExtension
SilverStripe\Security\Group:
  extensions:
    - SilverCommerce\ShoppingCart\Extensions\GroupExtension