---
Name: shoppingcartconfig
---
## Extensions
SilverStripe\Control\Controller:
  extensions:
    - SilverCommerce\ShoppingCart\Extensions\ControllerExtension
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - SilverCommerce\ShoppingCart\Extensions\SiteConfigExtension
SilverStripe\Security\Group:
  extensions:
    - SilverCommerce\ShoppingCart\Extensions\GroupExtension
SilverCommerce\OrdersAdmin\Model\Estimate:
  extensions:
    - SilverCommerce\ShoppingCart\Extensions\EstimateExtension
SilverCommerce\OrdersAdmin\Model\Invoice:
  extensions:
    - SilverCommerce\ShoppingCart\Extensions\InvoiceExtension
SilverStripe\Security\Member:
  extensions:
    - SilverCommerce\ShoppingCart\Extensions\MemberExtension