---
Name: shoppingcartconfig
---
## Extra DB fields
SilverStripe\Security\Member:
  has_one:
    Cart: SilverCommerce\ShoppingCart\Model\ShoppingCart

## Extensions
SilverStripe\Control\Controller:
  extensions:
    - SilverCommerce\ShoppingCart\Extensions\ControllerExtension
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - SilverCommerce\ShoppingCart\Extensions\SiteConfigExtension